shiweite/home/urls.py
"""
# -*- coding: utf-8 -*-
-------------------------------------------------
# @Project  :shiweite
# @File     :urls.py
# @Date     :2021/9/27 17:45
# @Author   :turbo
# @Email    :2647387166
# @Software :PyCharm
-------------------------------------------------
"""
from django.contrib import admin
from home.views import *
from django.urls import path, include

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('detail/',DetailView.as_view(),name='detail')
]

shiweite/shiweite/urls.py
from django.views.static import serve as static_serve
from django.contrib.staticfiles.views import serve #static静态文件
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
# 1 导入系统logging
# import logging
# #
# # # 2 创建日志署
# logger = logging.getLogger('django_log')
#
def return_static(request, path, insecure=True, **kwargs):
    return serve(request, path, insecure, **kwargs)

#
# def test_log(request):
#     # 3 调用日志器记录日志
#     logger.info('我是一条日志信息')
#     return HttpResponse('日志记录测试')

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', test_log)
    # include 参数1 要设置元组(urlconf_module,app_name). urlconf_module：子应用路由；app_name：子应用名
    # include 参数2 namespace 设置命名空间。这里设置子应用名
    path('',include(('users.urls','users'),namespace='users')),
    path('',include(('home.urls','home'),namespace='home')),
    path('',include(('errors.urls','errors'),namespace='errors')),
    url(r'^static/(?P<path>.*)$', return_static, name='static'),
    url(r'^media/(?P<path>.*)$', static_serve, {'document_root': settings.MEDIA_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shiweite/users/urls.py
from django.contrib import admin
from users.views import *
from django.urls import path, include

urlpatterns = [
    # 参数1：路由
    # 参数2：视图函数
    # 参数3：路由名，方便通过reverse来获取路由
    path('register/', RegisterView.as_view(), name='register'),
    # 图片验证码路由
    path('imagecode/',ImageView.as_view(),name='imagecode'),
    path('smscode/', SmsCodeView.as_view(),name='smcode'),
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('forgetpassword/', ForgetPasswordView.as_view(), name='forgetpassword'),
    path('usercenter/', UserCenterView.as_view(), name='usercenter'),
    path('writeblog/', WriteBlogView.as_view(), name='writeblog'),
    path('allblog/', AllblogView.as_view(), name='allblog'),
    path('personalblog/', PersonalblogView.as_view(), name='personalblog'),
]

shiweite/templates/allblog.html
{% extends 'base.html' %}

{% block title %}
    个人博客中心
{% endblock %}

{% block content_left %}
    <div class="col-md-9 cl-left">
        <p style="font-family: 楷体;text-align: center;font-size: 40px">{{ context }}</p>
        {% for article in all_blog %}
            <div class="cl-card">
                <div class="row">
                    <div class="col-lg-3 col-md-4 col-sm-12 cl-card-image"><a
                            href="{% url 'home:detail' %}?art_id={{ article.id }}"><img
                            src="{{ article.avatar.url }}" class="img-fluid" alt=""></a></div>
                    <div class="col-lg-9 col-md-8 col-sm-12 cl-card-main">
                        <h3 class="cl-card-main-title"><a
                                href="{% url 'home:detail' %}?art_id={{ article.id }}">{{ article.title }}</a>
                        </h3>
                        <p class="cl-card-main-info">
                            {{ article.sumary }}
                        </p>
                        <p class="cl-card-more"><a
                                href="{% url 'home:detail' %}?art_id={{ article.id }}">阅读更多...</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
        {#分页#}
{#        <nav aria-label="Page navigation example">#}
{#            <ul class="pagination justify-content-center">#}
                {# has_previous True如果有上一页，则返回#}
{#                {% if all_blog.has_previous %}#}
{#                    <li class="page-item">#}
{#                        <a class="page-link"#}
{#                           href="?page_index={{ all_blog.previous_page_number }}"#}
{#                           aria-label="Previous">#}
{#                            <span aria-hidden="true">上一页</span>#}
{#                            <span class="sr-only">上一页</span>#}
{#                        </a>#}
{#                    </li>#}
{#                {% else %}#}
{#                    <li class="page-item disabled">#}
{#                        <a class="page-link" href="#" aria-label="Previous">#}
{#                            <span aria-hidden="true">上一页</span>#}
{#                            <span class="sr-only">上一页</span>#}
{#                        </a>#}
{#                    </li>#}
{#                {% endif %}#}
                {#  articles.paginator.page_range  返回当前数据的 页码迭代器。 #}
{#                {% for num in all_blog.paginator.page_range %}#}
{#                    {% if num %}#}
{#                        {% ifequal num all_blog.number %}#}
{#                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>#}
{#                        {% else %}#}
{#                            <li class="page-item"><a class="page-link"#}
{#                                                     href="?page_index={{ num }}">{{ num }}</a>#}
{#                            </li>#}
{#                        {% endifequal %}#}
{#                    {% else %}#}
{#                        <li class="disabled"><a href="#">...</a></li>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
                {# has_next True如果有下一页则返回#}
{#                {% if all_blog.has_next %}#}
{#                    <li class="page-item">#}
{#                        <a class="page-link"#}
{#                           href="?page_index={{ all_blog.next_page_number }}"#}
{#                           aria-label="Next">#}
{#                            <span aria-hidden="true">下一页</span>#}
{#                            <span class="sr-only">下一页</span>#}
{#                        </a>#}
{#                    </li>#}
{#                {% else %}#}
{#                    <li class="page-item disabled">#}
{#                        <a class="page-link" href="#" aria-label="Next">#}
{#                            <span aria-hidden="true">下一页</span>#}
{#                            <span class="sr-only">下一页</span>#}
{#                        </a>#}
{#                    </li>#}
{#                {% endif %}#}
{#                <li class="page-item disabled">#}
{#                    <a href="#" class="page-link">共计：{{ all_blog.paginator.count }} 条</a>#}
{#                </li>#}
{#            </ul>#}
{#        </nav>#}

    </div>
{% endblock %}

shiweite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/cl-css.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'highlight/styles/railscasts.css' %}">
    <style>
        .class1 {
            font-family: 华文行楷;
            font-size: 45px;
            color: #8b98ab;
        }
    </style>
</head>
<body>
<div id="app">
    {#    导航栏    navdar navbar-expand-lg navbar-light#}
    <div class="cl-header container-fluid">
        <div class="header-content container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand" href="/">
                    <img src="../static/img/lhr.jpg" width="75" height="75" alt="">
                </a><span class="class1">筱宸</span>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        {% for cat in categories %}
                            {% if cat.id == category.id %}
                                <li class="nav-item active">
                                    <a class="nav-link" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <li class="nav-item dropdown" v-if="is_login">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-expanded="false">
                                {{ username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
                                <a class="dropdown-item" href="{% url 'users:usercenter' %}">个人信息</a>
                                <a class="dropdown-item" href="{% url 'users:allblog' %}">全部博客</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">退出</a>
                            </div>
                        </li>
                        <li class="nav-item" v-else>
                            <span class="nav-link"><a href="{% url 'users:login' %}">登录</a>/<a
                                    href="{% url 'users:register' %}">注册</a></span>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>
{#内容#}
<div class="cl-cantainer container">
    <div class="row">
        {#        内容左侧#}
        {% block content_left %}

        {% endblock %}
        {#    内容右侧#}
        <div class="col-md-3 cl-right">
            <div class="right-card">

                <div class="right-card-main">
                    <div style="font-family: Forte;font-size: 40px;text-align: center " class="right-card-title">turbo
                    </div>
                    <div style="font-family: 方正舒体;font-size: 45px" class="cl-code">
                        <p>心&nbsp;之&nbsp;所&nbsp;向</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;</p>
                        <p>不&nbsp;负&nbsp;热&nbsp;爱</p>
                    </div>
                </div>
            </div>

            <div class="right-card">
                <div class="right-card-main">
                    <div class="right-card-title">最新文章</div>
                    {% for new_art in new_arts %}
                        {% if new_art.id == arts_max %}
                            <div class="right-recommended"><a
                                    href="{% url 'home:detail' %}?art_id={{ new_art.id }}"><img
                                    src="{{ new_art.avatar.url }}" class="img-fluid" alt=""></a></div>
                        {% endif %}
                    {% endfor %}

                    <ul class="right-recommended-list">

                        {% for new_art in new_arts %}
                            <li><a href="{% url 'home:detail' %}?art_id={{ new_art.id }}"><i class="fa fa-angle-right"
                                                                                             aria-hidden="true"></i>{{ new_art.title }}
                            </a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="right-card">
                <div class="right-card-main">
                    <div class="right-card-title">热门标签</div>
                    <ul class="label">
                        {% for hot_tag in hot_tags %}
                            <li><a href="#">{{ hot_tag.tags }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid cl-footer">
        <div class="container">
            <p class="cl-copyright">本设计由然 ● 工作室荣誉出品</p>
            <p class="cl-copyright">turbo @ 2021 & 联系我们：hui20010207@163.com </p>
        </div>

    </div>
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'highlight/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    {% block js %}

    {% endblock %}
    <script src="{% static 'js/common.js' %}"></script>
    <script src="{% static 'js/host.js' %}"></script>
    <script src="{% static 'vue/vue-2.5.16.js' %}"></script>
    <script src="{% static 'vue/axios-0.18.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
</body>
</html>

shiweite/templates/details.html
{% extends 'base.html' %}

{% block title %}
    博客详情
{% endblock %}
{% load static %}
{% block content_left %}
    <div class="col-md-9 cl-left">

        <div class="cl-cantainer container">
            <div class="row">
                <div class="col-md-12 cl-left">
                    <div class="cl-artical-content">
                        <h2 class="cl-artical-title">{{ article.title }}</h2>
                        <div class="cl-card-tag">
                            <div><span>作者：<a data-toggle="tooltip" data-placement="top" title='查看该作者的全部博客' href="{% url 'users:personalblog' %}?per_id={{ article.author_id }}">{{ article.author.username }}</a></span></div>
                            <div><span>{{ article.total_views }}</span>人浏览 / <span>{{ article.comments_count }}</span>人评论
                            </div>
                            <div><span>发布时间：{{ article.create_time }}</span></div>
                        </div>
                        <img src="{{ article.avatar.url }}" class="img-fluid" alt="">
                        <div class="cl-artical">
                            {{ article.content | safe }}
                        </div>
                    </div>


                    <div class="recommend-panel">
                        <h4 class="right-card-title">相关文章</h4>
                        <div class="card-deck">

                            {% for corrtag in corrtags %}
                                {% if corrtag.id != article.id %}
                                    <div class="card ll-panel">
                                        <a class="recommend-panel-link"
                                           href="{% url 'home:detail' %}?art_id={{ corrtag.id }}">
                                            <div class="recommend-panel-top">
                                                <img src="{{ corrtag.avatar.url }}" class="img-fluid" alt="">
                                            </div>
                                            <div class="recommend-panel-bottom">
                                                {{ corrtag.sumary }}
                                            </div>
                                        </a>
                                    </div>
                                {% endif %}

                            {% endfor %}
                        </div>
                    </div>
                    {#             文章评论#}
                    <div class="comment">
                        <form class="cl-comment-from" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="art_id" value="{{ article.id }}">
                            <div><textarea placeholder="目前还不能评论哦QAQ！！！" rows="5" name="content"></textarea></div>
                            <button type="submit" disabled>留言</button>
                            <span class="clearfix"></span>
                        </form>


                        <h4 class="right-card-title">全部评论</h4>
                        {% for comm in comms %}
                            <div class="comment-panel">
                                <div class="comment-panel-portrait">
                                    {% if comm.user.avatar %}
                                        <img src="{{ comm.user.avatar.url }}" class="img-fluid rounded-circle" alt="">
                                    {% else %}
                                        <img src="{% static 'img/portrait.png' %}" alt="">
                                    {% endif %}
                                </div>
                                <div class="comment-panel-content">
                                    <div class="comment-panel-content-item">
                                        <div class="comment-author">{{ comm.user.username }}</div>
                                        <div>{{ comm.created_time }}</div>
                                    </div>
                                    <div class="comment-panel-content-main">{{ comm.content }}</div>
                                </div>
                                <span class="clearfix"></span>
                                {#                        <div class="text-primary"><a href="">回复</a></div>#}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

shiweite/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登录</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/cl-css.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'highlight/styles/railscasts.css' %}">
</head>
<body>
<div id="app">
    <div class="cl-header container-fluid">
        <div class="header-content container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand" href="/">
                    <img src="../static/img/turbo.jpg" width="75" height="75" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
{#                            <a class="nav-link" href="index.html">首页 <span class="sr-only">(current)</span></a>#}
                        </li>
                        <li class="nav-item">
{#                            <a class="nav-link" href="#">教程</a>#}
                        </li>
                        <li class="nav-item">
{#                            <a class="nav-link" href="#">模板</a>#}
                        </li>
                        <li class="nav-item">
{#                            <a class="nav-link" href="#">日记</a>#}
                        </li>
                        <li class="nav-item">
{#                            <a class="nav-link" href="#">关于</a>#}
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="cl-cantainer container pt-5">
        <form class="col-md-6 offset-md-3" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail4">手机号码</label>
                <input type="number" class="form-control" id="mobile" name="mobile" placeholder="请输入手机号"
                       autofocus="autofocus" required v-model="mobile" @blur="check_mobile">
                <small class="form-text  ml-1">还没有账号，<a href="{% url 'users:register' %}" class="text-primary">注册新账号</a></small>
                <small class="form-text text-danger ml-1" v-show="mobile_error">[[mobile_error_message]]</small>
            </div>
            <div class="form-group">
                <label for="id_password">密码</label>
                <input type="password" class="form-control" id="id_password" name="password" placeholder="请输入密码"
                       required class="form-control" v-model="password" @blur="check_password"/>
                <small class="form-text  ml-1"><a href="{% url 'users:forgetpassword' %}" class="text-primary">忘记密码？</a></small>
                <small class="form-text text-danger ml-1" v-show="password_error">[[password_error_message]]</small>
            </div>
            <div class="form-group">
                <input type="checkbox" name="remember">保持2周登录
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">登录</button>
            </div>
            <div class="form-group">
                <p class="text-danger">{{ msg }}</p>
            </div>
        </form>
    </div>
    <div class="container-fluid cl-footer">
        <div class="container">
            <p class="cl-copyright">本设计由然 ● 工作室荣誉出品</p>
            <p class="cl-copyright">turbo @ 2021 & 联系我们：hui20010207@163.com </p>
        </div>
    </div>
</div>
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'highlight/highlight.pack.js' %}"></script>
<script src="{% static 'vue/vue-2.5.16.js' %}"></script>
<script src="{% static 'js/host.js' %}"></script>
<script src="{% static 'js/register.js' %}"></script>
<script src="{% static 'vue/axios-0.18.0.min.js' %}"></script>
<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>

shiweite/templates/writeblog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>写博客</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/cl-css.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'highlight/styles/railscasts.css' %}">
    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}" type="text/javascript" charset="UTF-8"></script>
</head>
<body>
<div class="cl-header container-fluid" id="app">
    <div class="header-content container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="index.html">
                <img src="../static/img/turbo.jpg" width="75" height="75" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">

                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item dropdown" v-if="is_login">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">{{username}}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block"
                             v-show="show_menu">
                            <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章 </a>
                            <a class="dropdown-item" href='{% url 'users:usercenter' %}'>个人信息 </a>
                            <a class="dropdown-item" href='{% url 'users:logout' %}'> 退出登录</a>
                        </div>
                    </li>
                    <!-- 如果用户未登录，则显示登录按钮 -->
                    <li class="nav-item" v-else>
                        <a class="nav-link" href="{% url 'users:login' %}"> 登录</a>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
</div>

<div class="cl-cantainer container pt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group carousel-inner">
            <label for="avatar">标题插图</label><br>
            <label>
                <input type="file" name="avatar" id="image-input">
            </label>
            <div id="div1" class="card" style="max-height: 550px ;max-width: 550px"></div>

        </div>
        <div class="form-group">
            <label for="">文章标题</label>
            <input type="text" class="form-control" id="" name="title" required class="form-control"/>
        </div>

        <!-- 文章栏目 -->
        <div class="form-group">
            <label for="column">栏目</label>
            <select class="form-control" id="category_id" name="category_id">
                {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.title }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="">标签</label>
            <input type="text" id="" name="tags" required class="form-control"/>
        </div>
        <div class="form-group">
            <label for="">文章摘要</label>
            <input type="text" id="" name="sumary" required class="form-control"/>
        </div>
        <div class="form-group">
            <label for="">文章正文</label>
            <textarea name="content" id="editor1" rows="10" cols="80"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">完成</button>
        </div>
    </form>

</div>
<div class="container-fluid cl-footer">
    <div class="container">
        <p class="cl-copyright">本设计由然 ● 工作室荣誉出品</p>
        <p class="cl-copyright">turbo @ 2021 & 联系我们：hui20010207@163.com </p>
    </div>
</div>

</body>
<script src="../static/jquery/jquery.min.js"></script>
<script src="../static/bootstrap/js/bootstrap.min.js"></script>
<script src="../static/highlight/highlight.pack.js"></script>
<script src="../static/vue/vue-2.5.16.js"></script>
<script src="../static/js/host.js"></script>
<script src="../static/js/common.js"></script>
<script src="../static/js/index.js"></script>
<script src="../static/jquery/jquery.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<script>
    CKEDITOR.replace('editor1')
</script>

<script>
    $(function () {
        $("#image-input").on("change", writeblog);
    })
    function writeblog() {
        var formdata = new FormData();
        {#formdata.append("image", $("#image-input").prop('files')[0]);#}
        formdata.append("image", $("#image-input")[0].files[0]);
        formdata.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        $.ajax({
            processData: false,
            contentType: false,
            url: '/writeblog/',
            type: 'post',
            data: formdata,
            dataType: "json",
            success: function (arg) {
                $('#div1').empty();
                $('#div1').append(
                    "<img class='img-fluid' src=' " + arg.url + " ' > "
                )
                if (arg.state === 1) {
                    alert('上传成功！')
                } else {
                    alert('上传失败！')
                }
            }, error: function () {
                alert("访问繁忙，请重试")
            }
        })
    }

</script>

</html>